### PR TITLE
Topic permissions support

### PR DESCRIPTION
**Pull request by BarnabyShearer**
RabbitMQ >= 3.7.0 added a type of permission. These match topics within an exchange instead of queues. This PR implements a Terraform resource for managing them.
It includes an update to the vendored `rabbit-hole` for the necessary API support.

### CODE REVIEW

**Comment by khadrawy** [comment]
Any plans on merging this pr in near future?

**Comment by amir-hadi** [comment]
This is needed desperately. This is now waiting quite some bit.

**Review by cyrilgdn — CHANGES_REQUESTED** [review]
@BarnabyShearer Thanks for your work and for opening this PR.

@BarnabyShearer  @khadrawy @amir-hadi I was added a maintainer of this provider few weeks ago as there were no more active maintainers on it.
I didn't have the time to go around all the opened issues/PRs yet but I'll try to take a look at this one in  the next days.

@BarnabyShearer Multiple modifications has been made on the provider since your PR (Upgrade to new Terraform SDK plugin, vendors update, etc...)

Could you already rebase your branch on master? 

Also you have modified files in vendors directory but you didn't change anything in `go.mod` file which is not normal. Anyway `rabbit-hole` is now in v1.5.0 in `master` so after your rebase you'll probably don't need these vendors changes anymore.

**Comment by amir-hadi** [comment]
@cyrilgdn Thank you very much for driving this forward.

**Comment by BarnabyShearer** [comment]
Rebased in #49

**Pull request closed without merging**
