### PR TITLE
resource/rabbitmq_user - fix password issue when updating user tags

### LINKED ISSUE #40: rabbitmq_user - updating tags clears password
### Terraform Version
Terraform v0.12.9

### Affected Resource(s)
- rabbitmq_user

### Terraform Configuration Files
```hcl
resource "rabbitmq_user" "test" {
  name     = "mctest"
  password = "foobarry"
  tags = [
    "admin",
    "management",
  ]
}
```

### Expected Behavior
Updating user tags shouldn't clear the user password

### Actual Behavior
When updating the tags for an existing user, it seems like the provider doesn't pass the password in the PUT request, which essentially leads to the user not being able to authenticate. This can currently only be resolved by:
1) Updating the user password in the management console
2) Re-creating the user with Terraform

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` the above configuration
2. Try to log in (works)
3. Update the list of tags and run `terraform apply`
4. Try to log in (does not work)

### PR DESCRIPTION
**Pull request by heimweh**
This PR fixes #40 by setting the password in the user settings. 
Without this, any changes to the tags will break the password for an existing user.

### CODE REVIEW

**Comment by heimweh** [comment]
Tests are passing:

```bash
$ make testacc TEST=./rabbitmq
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./rabbitmq -v -count=1 -timeout 120m
=== RUN   TestAccBinding_importBasic
--- PASS: TestAccBinding_importBasic (0.46s)
=== RUN   TestAccExchange_importBasic
--- PASS: TestAccExchange_importBasic (0.38s)
=== RUN   TestAccPermissions_importBasic
--- PASS: TestAccPermissions_importBasic (0.35s)
=== RUN   TestAccPolicy_importBasic
--- PASS: TestAccPolicy_importBasic (0.41s)
=== RUN   TestAccQueue_importBasic
--- PASS: TestAccQueue_importBasic (0.36s)
=== RUN   TestAccUser_importBasic
--- PASS: TestAccUser_importBasic (0.06s)
=== RUN   TestAccVhost_importBasic
--- PASS: TestAccVhost_importBasic (0.32s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccBinding_basic
--- PASS: TestAccBinding_basic (0.41s)
=== RUN   TestAccBinding_slashEscaping
--- PASS: TestAccBinding_slashEscaping (0.45s)
=== RUN   TestAccBinding_propertiesKey
--- PASS: TestAccBinding_propertiesKey (0.41s)
=== RUN   TestAccExchange
--- PASS: TestAccExchange (0.35s)
=== RUN   TestAccPermissions
--- PASS: TestAccPermissions (0.38s)
=== RUN   TestAccPolicy
--- PASS: TestAccPolicy (0.46s)
=== RUN   TestAccQueue_basic
--- PASS: TestAccQueue_basic (0.38s)
=== RUN   TestAccQueue_jsonArguments
--- PASS: TestAccQueue_jsonArguments (0.37s)
=== RUN   TestAccUser_basic
--- PASS: TestAccUser_basic (0.11s)
=== RUN   TestAccUser_emptyTag
--- PASS: TestAccUser_emptyTag (0.13s)
=== RUN   TestAccUser_noTags
--- PASS: TestAccUser_noTags (0.10s)
=== RUN   TestAccUser_passwordChange
--- PASS: TestAccUser_passwordChange (0.10s)
=== RUN   TestAccVhost
--- PASS: TestAccVhost (0.31s)
PASS
ok  	github.com/terraform-providers/terraform-provider-rabbitmq/rabbitmq	6.325s
```

**Review by mbfrahry — APPROVED** [review]
LGTM

**Comment by cyrilgdn** [comment]
@heimweh FYI #31 was already fixing this (and was adding some unit tests to assert this fix) .

**Comment by heimweh** [comment]
Hey @cyrilgdn,

Sorry! I must’ve completely missed your fix.
@mbfrahry can you take a look at #31 instead? 🙏

Best,

Alexander

**Comment by cyrilgdn** [comment]
Hi @heimweh ,

Actually I asked to become a maintainer of this repo (as I was already maintainer of another provider) so I'm now able to manager pull requests.
I'll close this one in favor of #31. 

As you worked on this, could you make a review of mine and if it's ok for you we'll merge it.

**Pull request closed without merging**
