### PR TITLE
Add more shovel parameters

### LINKED ISSUE #61: Rabbitmq Shovel definition is incomplete and invalid because the source and destination protocols are unspecified
### Terraform Version
0.13.3

### Affected Resource(s)
- rabbitmq_shovel

### Terraform Configuration Files
```hcl
resource "rabbitmq_shovel" "shovelTest" {
    name = "shovelTest"
    vhost = "${rabbitmq_vhost.test.name}"
    info {
        source_uri = "amqp:///test"
        source_exchange = "${rabbitmq_exchange.test.name}"
        source_exchange_key = "test"
        destination_uri = "amqp:///test"
        destination_exchange = "${rabbitmq_exchange.test.name}"
    }
}
```

### Expected Behavior
Valid Rabbitmq Shovel should have been created.

### Actual Behavior
Invalid Rabbitmq Shovel created due to empty Rabbitmq source/destination protocols (see attached screenshot of the Rabbitmq Management UI with empty source and destination protocol fields).

Screenshot 2020-09-21 at 11 49 32 AM

### Steps to Reproduce
`terraform apply` although I'm using the pulumi rabbitmq provider which wraps terraform: https://github.com/pulumi/pulumi-rabbitmq

### Important Factoids
We should update to use all the underlying rabbitmq shovel fields as the underlying rabbitmq go library has been updated (see reference PR below)

### References
Underlying rabbitmq library has been updated with all required fields. `Add missing Parameters for Shovels ` https://github.com/michaelklishin/rabbit-hole/pull/157

### PR DESCRIPTION
**Pull request by akurz**
Hello,

as promised :-) I prepared a pull request to update the shovel resource. It passes all tests and works in our environment. 

With this update it is possible to use all available parameters for dynamic shovels. For this to work I also sent a patch to rabbit-hole which was merged and is available since v2.3.0. 

As the provider currently supports some deprecated parameters that do not show up anymore in the RabbitMQ documentation I followed https://www.terraform.io/docs/extend/best-practices/deprecations.html#renaming-an-optional-attribute and added Deprecated/ConflictsWith and warnings to the docs. If I understand it correctly, best practice would be to release (at least?) one minor release of the provider before removing those deprecated parameters completely. 

Please let me know if the patches are fine (I am not a developer ...) - any feedback is highly appreciated.

Thanks & Cheers,
Andreas

### CODE REVIEW

**Comment by akurz** [comment]
ping @cyrilgdn :-)

**Comment by AgrimPrasad** [comment]
This closes #61 

Can we please progress this issue as the current shovel is completely invalid due to missing source/destination protocols? Thanks.

@cyrilgdn

**Comment by AgrimPrasad** [comment]
@cyrilgdn There are several people waiting on this PR. Could you please review it? Many thanks!

**Review by cyrilgdn — APPROVED** [review]
Hi @akurz ,

Thanks for your work on that and really sorry for the delay.

As I never used shovel I'll trust you and the tests to assert that it works.

The code seems good to me.

**Pull request merged**
