### PR TITLE
Upgrade rabbit hole v2.2.0

### PR DESCRIPTION
**Pull request by niclic**
This is simply an upgrade from `v2.1.0` to `v2.2.0`. Lots of changes to the vendor modules. The upstream changes can be seen in this [commit](https://github.com/michaelklishin/rabbit-hole/commit/95a7372bfcb42b91861c24f41f603c6da96fc596).

I originally made this change in this [PR](https://github.com/terraform-providers/terraform-provider-rabbitmq/pull/55), but I thought it would be easier to reason about if separated.

All tests pass.

@cyrilgdn

### CODE REVIEW

**Comment by niclic** [comment]
It might be time to retire support for the 3.6 branch, since it fell out of support (i.e. reached EOL) exactly 2 years ago.

**Comment by niclic** [comment]
Persistent build failures can be resolved with https://github.com/terraform-providers/terraform-provider-rabbitmq/pull/58

**Review by cyrilgdn — COMMENTED** [review]
I merged #58 , just need to rebase (could you squash in one commit at the same time please?) this one and it should be good :+1:

**Comment by niclic** [comment]
Will do!

**Comment by niclic** [comment]
Should be good now @cyrilgdn

**Review by cyrilgdn — APPROVED** [review]
:+1:

**Pull request merged**
