### PR TITLE
Implementation of arguments_json in Bindings

### PR DESCRIPTION
**Pull request by nanernunes**
I'm using the `arguments_json` created by @jtopjian and @appilon on queue resource but I figure out this resource wasn't implemented on bindings. This pull request adds this feature because I'm facing a scenario where it's necessary to configure a binding object with a list of binding params that is an array of strings, but the current implementation only allows strings as value.

This is an example of the configuration in binding objects with the `arguments_json` feature:
```hcl
resource "rabbitmq_binding" "binding_test" {
  source           = "exchange_test"
  vhost            = "/"
  destination      = "queue_test"
  destination_type = "queue"
  routing_key      = ""
  arguments_json = <<EOF
    {
      "x-match": "any",
      "key": ["value1", "value2"]
    }
  EOF
}
```

### CODE REVIEW

**Comment by LTMenezes** [comment]
+1
Thanks! I was looking for this feature too.

@radeksimko Can you take a look into this?

**Comment by digmunhoz** [comment]
+1

**Comment by dnp1** [comment]
+1 here

**Comment by cyrilgdn** [comment]
Oops, I fail the rebase and it closed the PR by error :facepalm: 

Thanks for your work on that @nanernunes and sorry for the delay. There were no more maintainers on this provider and it took me a while to catch up.

It looks good to me, I'll merge it (rebased on master) in #59

**Pull request closed without merging**
