### PR TITLE
Adding client certificate authentication

### LINKED ISSUE #24: Support for client certificate authentication
Hi there,

are there any plans for supporting client certificate authentication?
Or is there an undocumented argument to provide a client certificate?

https://www.terraform.io/docs/providers/rabbitmq/index.html

Kind regards,
Adam

### PR DESCRIPTION
**Pull request by sam-dumont**
Hi,

For my own project, I need to be able to use client certificate authentication. This change is working well, altough not supporting (yet) passphrase protected keys.

This could also be implemented, I can do it if needed https://medium.com/@prateeknischal25/using-encrypted-private-keys-with-golang-server-379919955854

I'm not the only one needing this : fix #24 . I think it would be good for the official provider to support it.

Regards,

Samuel

### CODE REVIEW

**Review by cyrilgdn — CHANGES_REQUESTED** [review]
Hi @samueldumont ,

Thanks for your work on this and sorry for the response delay.

The code looks good to me :+1: , I'll trust you on the fact that it works as it's not very easy to test :smile: 

Could you just remove the ``.version`` and ``build.sh`` files as we don't need them (you can add them in your gitignore file if you want to keep them for your own purpose).

**Comment by sam-dumont** [comment]
Hi @cyrilgdn !

Thanks a lot, it works perfectly fine indeed, we used my fork for a year with no issues ;) I'm glad this can go back to the main provider so we don't have to mess anymore with custom providers.

I removed the files so it should be good now

**Review by cyrilgdn — APPROVED** [review]
@samueldumont Perfect, thanks !

And sorry again for the delay, there were no more active maintainer on this provider and it took me a bit of time to go through opened issues/PRs since I've been added as a maintainer.

I'll let you know here when it's released.

**Comment by cyrilgdn** [comment]
@samueldumont FYI, this has just been released in [v1.4.0](https://github.com/terraform-providers/terraform-provider-rabbitmq/blob/master/CHANGELOG.md#140-july-17-2020).

**Comment by sam-dumont** [comment]
Thank you very much !

**Pull request merged**
